# Generated by Django 5.1.6 on 2025-12-08 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='avatar_choice',
            field=models.CharField(choices=[('avatar_1.jpg', 'Avatar 1'), ('avatar_2.jpg', 'Avatar 2'), ('avatar_3.jpg', 'Avatar 3'), ('avatar_4.jpg', 'Avatar 4'), ('avatar_5.jpg', 'Avatar 5'), ('avatar_6.jpg', 'Avatar 6'), ('avatar_7.jpg', 'Avatar 7')], default='avatar_1.jpg', help_text='Escolha um dos avatares padrão disponíveis', max_length=20, verbose_name='Avatar Padrão'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='custom_avatar',
            field=models.CharField(blank=True, help_text='URL ou caminho do avatar personalizado (apenas VIP)', max_length=255, null=True, verbose_name='Avatar Personalizado'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='custom_banner',
            field=models.CharField(blank=True, help_text='URL ou caminho do banner personalizado (apenas VIP)', max_length=255, null=True, verbose_name='Banner Personalizado'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='is_vip',
            field=models.BooleanField(default=False, help_text='Marca se o usuário tem privilégios VIP (avatar/banner personalizados)', verbose_name='É VIP'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Avatar do usuário (recomendado: 200x200px) - DEPRECATED: use avatar_choice', null=True, upload_to='avatars/%Y/%m/'),
        ),
    ]
