# Generated by Django 5.2.8 on 2025-11-18 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo_busca', models.CharField(max_length=255)),
                ('filtros', models.JSONField(blank=True, default=dict)),
                ('executado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de busca',
                'verbose_name_plural': 'Logs de busca',
                'ordering': ['-executado_em'],
            },
        ),
        migrations.CreateModel(
            name='AnimeSyncStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_payload', models.JSONField(blank=True, default=dict)),
                ('etag', models.CharField(blank=True, max_length=255)),
                ('anime', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_status', to='anime.anime')),
            ],
            options={
                'verbose_name': 'Status de sincronização do anime',
                'verbose_name_plural': 'Status de sincronização dos animes',
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('MAL', 'MyAnimeList')], default='MAL', max_length=10)),
                ('tipo', models.CharField(choices=[('FULL_IMPORT', 'Importação completa'), ('ATUALIZAR_TEMPORADA', 'Atualizar temporada'), ('ATUALIZAR_ANIME', 'Atualizar anime')], max_length=30)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUCESSO', 'Sucesso'), ('ERRO', 'Erro')], max_length=10)),
                ('mensagem', models.TextField(blank=True)),
                ('qtd_animes_atualizados', models.IntegerField(default=0)),
                ('temporada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to='anime.temporada')),
            ],
            options={
                'verbose_name': 'Log de sincronização',
                'verbose_name_plural': 'Logs de sincronização',
                'ordering': ['-started_at'],
            },
        ),
    ]
