# Generated by Django 5.1.6 on 2025-12-02 04:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_id', models.IntegerField(help_text='ID do anime no MyAnimeList')),
                ('texto', models.TextField(help_text='Texto do comentário (máx 2000 caracteres)', max_length=2000)),
                ('nota', models.IntegerField(blank=True, help_text='Nota de 1 a 10 (opcional)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_anime', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['anime_id', '-criado_em'], name='comentarios_anime_i_cb767d_idx'), models.Index(fields=['user', '-criado_em'], name='comentarios_user_id_c31901_idx')],
            },
        ),
    ]
