# Generated by Django 5.1.6 on 2025-12-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete: marca como deletado sem remover'),
        ),
    ]
