# Generated by Django 5.2.8 on 2025-11-18 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_id', models.IntegerField(unique=True, verbose_name='ID do MyAnimeList')),
                ('titulo', models.CharField(max_length=255)),
                ('titulo_ingles', models.CharField(blank=True, max_length=255)),
                ('sinopse', models.TextField(blank=True)),
                ('imagem_url', models.URLField(blank=True)),
                ('trailer_url', models.URLField(blank=True)),
                ('tipo', models.CharField(choices=[('TV', 'TV'), ('MOVIE', 'Filme'), ('OVA', 'OVA'), ('SPECIAL', 'Especial')], default='TV', max_length=20)),
                ('status', models.CharField(choices=[('EM_LANCAMENTO', 'Em lançamento'), ('FINALIZADO', 'Finalizado'), ('PAUSADO', 'Pausado')], default='EM_LANCAMENTO', max_length=20)),
                ('episodios_total', models.IntegerField(blank=True, null=True)),
                ('data_lancamento', models.DateField(blank=True, null=True)),
                ('data_encerramento', models.DateField(blank=True, null=True)),
                ('nota_mal', models.FloatField(blank=True, null=True)),
                ('popularidade_score', models.IntegerField(default=0)),
                ('membros_mal', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Anime',
                'verbose_name_plural': 'Animes',
                'ordering': ['-data_lancamento', '-nota_mal'],
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Gênero',
                'verbose_name_plural': 'Gêneros',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('site_oficial', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Estúdio',
                'verbose_name_plural': 'Estúdios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='AnimeAiring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episodio', models.IntegerField(blank=True, null=True)),
                ('data_exibicao', models.DateField()),
                ('hora_exibicao', models.TimeField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airings', to='anime.anime')),
            ],
            options={
                'verbose_name': 'Exibição',
                'verbose_name_plural': 'Exibições',
                'ordering': ['data_exibicao', 'hora_exibicao'],
            },
        ),
        migrations.CreateModel(
            name='AnimeGenero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.anime')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.genero')),
            ],
            options={
                'verbose_name': 'Gênero do anime',
                'verbose_name_plural': 'Gêneros do anime',
                'unique_together': {('anime', 'genero')},
            },
        ),
        migrations.AddField(
            model_name='anime',
            name='generos',
            field=models.ManyToManyField(blank=True, related_name='animes', through='anime.AnimeGenero', to='anime.genero'),
        ),
        migrations.CreateModel(
            name='AnimeStudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.anime')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.studio')),
            ],
            options={
                'verbose_name': 'Estúdio do anime',
                'verbose_name_plural': 'Estúdios do anime',
                'unique_together': {('anime', 'studio')},
            },
        ),
        migrations.AddField(
            model_name='anime',
            name='studios',
            field=models.ManyToManyField(blank=True, related_name='animes', through='anime.AnimeStudio', to='anime.studio'),
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('estacao', models.CharField(choices=[('INVERNO', 'Inverno'), ('PRIMAVERA', 'Primavera'), ('VERAO', 'Verão'), ('OUTONO', 'Outono')], max_length=10)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('is_atual', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Temporada',
                'verbose_name_plural': 'Temporadas',
                'ordering': ['-ano', 'estacao'],
                'unique_together': {('ano', 'estacao')},
            },
        ),
        migrations.AddField(
            model_name='anime',
            name='temporada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animes', to='anime.temporada'),
        ),
    ]
