# Generated by Django 5.1.6 on 2025-12-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='titulo_ingles',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
